// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJXT42bw0Tq0gCm3_HZR570TYBSLdgQMg',
    appId: '1:1089895449096:web:7552a7bec7bfe0ab0707bd',
    messagingSenderId: '1089895449096',
    projectId: 'life-notebook-fd44f',
    authDomain: 'life-notebook-fd44f.firebaseapp.com',
    storageBucket: 'life-notebook-fd44f.firebasestorage.app',
    measurementId: 'G-G9Z7116CC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXrL5LBoh2aqSrTAy0UKiAxD1p_doLQc0',
    appId: '1:1089895449096:android:a1d8f6b7aef839160707bd',
    messagingSenderId: '1089895449096',
    projectId: 'life-notebook-fd44f',
    storageBucket: 'life-notebook-fd44f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMEB2Unanp4pB7tD2zmjK4BXMiBPlpfxQ',
    appId: '1:1089895449096:ios:7c54961c03311a890707bd',
    messagingSenderId: '1089895449096',
    projectId: 'life-notebook-fd44f',
    storageBucket: 'life-notebook-fd44f.firebasestorage.app',
    iosBundleId: 'com.example.notDefterim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMEB2Unanp4pB7tD2zmjK4BXMiBPlpfxQ',
    appId: '1:1089895449096:ios:7c54961c03311a890707bd',
    messagingSenderId: '1089895449096',
    projectId: 'life-notebook-fd44f',
    storageBucket: 'life-notebook-fd44f.firebasestorage.app',
    iosBundleId: 'com.example.notDefterim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJXT42bw0Tq0gCm3_HZR570TYBSLdgQMg',
    appId: '1:1089895449096:web:101ff07c1e0b31180707bd',
    messagingSenderId: '1089895449096',
    projectId: 'life-notebook-fd44f',
    authDomain: 'life-notebook-fd44f.firebaseapp.com',
    storageBucket: 'life-notebook-fd44f.firebasestorage.app',
    measurementId: 'G-4GTBS9CZHM',
  );
}
